### ISSUE TITLE
Error communicating with OpenAI!

### ISSUE THREAD

**Issue by yindahu87** [jiho283/KG-GPT#1]
Error: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcaebdf1610>: Failed to establish a new connection: [Errno 111] Connection refused'))

please tell me how to solve this problem,sincerely!

**Comment by jiho283** [comment]
I think there might be an error in your network. This issue seems to be unrelated to the KG-GPT framework and is associated with an error in the ChatGPT API call. I recommend contacting OpenAI for assistance.

**Comment by yindahu87** [comment]
已解决，感谢！
