### ISSUE TITLE
About the code

### ISSUE THREAD

**Issue by yindahu87** [jiho283/KG-GPT#4]
In the relation retrieval phase described in Figure 1 of your paper, are the relation candidates and topk relation implemented in the code of FactKG? I noticed that the code in MetaQA does not have this logic. Does MetaQA not require relationship candidates? Could you please clarify my confusion? Thank you very much.

**Comment by jiho283** [comment]
Thank you for your interest in KG-GPT! MetaQA also has a relation retrieval stage. For example, if you look at KG-GPT/metaqa/metaqa_2hop_test.py, you can see the implementation of the relation retrieval process from line 135 to line 176.

**Comment by yindahu87** [comment]
> Thank you for your interest in KG-GPT! MetaQA also has a relation retrieval stage. For example, if you look at KG-GPT/metaqa/metaqa_2hop_test.py, you can see the implementation of the relation retrieval process from line 135 to line 176.

Thank you for your reply. I understand that both FactKG and MetaQA have a relationship retrieval phase. However, I noticed that there is a function called `relation_candidates` in FactKG, which I did not see in MetaQA. The logic enclosed in the red box in the figure below, which involves retrieving the topk relationships from the relationship candidates, is also not present in MetaQA. Does this imply that MetaQA does not require relationship candidates and the logic of retrieving the topk relationships from those candidates?
![论文疑问](https://github.com/jiho283/KG-GPT/assets/102854011/a4679136-b78e-4050-9e1d-3b235b195c77)

**Comment by jiho283** [comment]
That's correct. In FactKG, relations for multi-hop claims are retrieved using a dictionary composed of the types of entities (in ```relation_candidates```). However, in MetaQA, all relations connected to the current entity are retrieved and used as relation candidates, so no separate function was written.

**Comment by yindahu87** [comment]
Okay, I understand, thank you for your answer.
