### ISSUE TITLE
Are that prompts for relation retrieval shown in the article are different from that in code? Which version should I take to reproduce the expriment result?

### ISSUE THREAD

**Issue by Xianyu39** [jiho283/KG-GPT#5]
I'am a student who wanna reproduce the expriment of your article to finish a task of a course and I am confused about the prompt for retrieving the top k most relevant relations from a set of relations.

Are that prompts for relation retrieval shown in the article are different from that in code? The article version ask LLM to select top k elements from words set while the code version not. Which version should I take to reproduce the expriment result?

**Comment by jiho283** [comment]
Thank you for your interest in KG-GPT. Both prompts work well, so it doesn’t matter which one you use. Since the prompt included in the code makes it easier to run experiments, feel free to use it directly.
